name: safewalk
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  flutter_tflite: ^1.0.1
  flutter_tts: ^3.8.5
  provider: ^6.1.1
  flutter_mobile_vision_2: ^0.1.9
  flutter_langdetect: ^0.0.2
  permission_handler: ^10.3.0
  speech_to_text: ^6.6.0
  flutter_local_notifications: ^16.3.2
  url_launcher: ^6.2.5
  geolocator: ^8.2.1	
  google_maps_flutter: ^2.2.8
  qr_code_scanner: ^1.0.1
  local_auth: ^2.2.0
  sensors_plus: ^4.0.2





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  
  uses-material-design: true
  assets:
    - assets/
 